//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReLearn.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReLearn.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter word!.
        /// </summary>
        public static string AddViewModel_EnterWord {
            get {
                return ResourceManager.GetString("AddViewModel.EnterWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word added!.
        /// </summary>
        public static string AddViewModel_WordAdded {
            get {
                return ResourceManager.GetString("AddViewModel.WordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word exists!.
        /// </summary>
        public static string AddViewModel_WordExists {
            get {
                return ResourceManager.GetString("AddViewModel.WordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entered incorrectly.
        /// </summary>
        public static string DictionaryReplenishmentViewModel_DataCorrectness {
            get {
                return ResourceManager.GetString("DictionaryReplenishmentViewModel.DataCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words have been added to your dictionary.
        /// </summary>
        public static string DictionaryReplenishmentViewModel_WordsAdded {
            get {
                return ResourceManager.GetString("DictionaryReplenishmentViewModel.WordsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string GeneralStatisticsViewModel_Average {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string GeneralStatisticsViewModel_Correct {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answers.
        /// </summary>
        public static string GeneralStatisticsViewModel_CorrectAnswers {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.CorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree of study.
        /// </summary>
        public static string GeneralStatisticsViewModel_DegreeOfStudy {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.DegreeOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect.
        /// </summary>
        public static string GeneralStatisticsViewModel_Incorrect {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string GeneralStatisticsViewModel_Month {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Ratio.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberCorrectAnswers {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberCorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of inconvenient films.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberInconvenientFilms {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberInconvenientFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of inconvenient flags.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberInconvenientFlags {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberInconvenientFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of inconvenient images.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberInconvenientImages {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberInconvenientImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of inconvenient words.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberInconvenientWords {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberInconvenientWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of films learned.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberLearnedFilms {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberLearnedFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of flags learned.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberLearnedFlags {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberLearnedFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of images learned.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberLearnedImages {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberLearnedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of words learned.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberLearnedWords {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberLearnedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of tests.
        /// </summary>
        public static string GeneralStatisticsViewModel_NumberOfTests {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.NumberOfTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string GeneralStatisticsViewModel_Of {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string GeneralStatisticsViewModel_Today {
            get {
                return ResourceManager.GetString("GeneralStatisticsViewModel.Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You repeated all the images.
        /// </summary>
        public static string HomeViewModel_RepeatedAllImages {
            get {
                return ResourceManager.GetString("HomeViewModel.RepeatedAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You repeated all the words.
        /// </summary>
        public static string HomeViewModel_RepeatedAllWords {
            get {
                return ResourceManager.GetString("HomeViewModel.RepeatedAllWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary over.
        /// </summary>
        public static string LearnViewModel_DictionaryOver {
            get {
                return ResourceManager.GetString("LearnViewModel.DictionaryOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string LearnViewModel_Next {
            get {
                return ResourceManager.GetString("LearnViewModel.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string MainStatisticsViewModel_Correct {
            get {
                return ResourceManager.GetString("MainStatisticsViewModel.Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string MainStatisticsViewModel_Incorrect {
            get {
                return ResourceManager.GetString("MainStatisticsViewModel.Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last testing.
        /// </summary>
        public static string MainStatisticsViewModel_LastTest {
            get {
                return ResourceManager.GetString("MainStatisticsViewModel.LastTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string MainViewModel_Learn {
            get {
                return ResourceManager.GetString("MainViewModel.Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string MainViewModel_Repeat {
            get {
                return ResourceManager.GetString("MainViewModel.Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsMenuViewModel_Cancel {
            get {
                return ResourceManager.GetString("SettingsMenuViewModel.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string SettingsMenuViewModel_ChooseLanguage {
            get {
                return ResourceManager.GetString("SettingsMenuViewModel.ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose pronunciation.
        /// </summary>
        public static string SettingsMenuViewModel_ChoosePronunciation {
            get {
                return ResourceManager.GetString("SettingsMenuViewModel.ChoosePronunciation", resourceCulture);
            }
        }
    }
}
