#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReLearn.Resource", IsApplication=true)]

namespace ReLearn
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_EditText = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backgroundEnFl = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backgroundMain = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_enabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_false = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Button_Speak = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_style_standard = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_touch = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_true = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int buttonAfterClicking = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int buttonBeforeClicking = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int buttonSpeech = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dictionary = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int EditText_style = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_new = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int iconSpeak = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int mainBackGround = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MainRelearn = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int relearnMain = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int settings = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int speak_off = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int speak_on = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Stat1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Stat2 = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07003a
			public const int ABC = 2131165242;
			
			// aapt resource value: 0x7f07001a
			public const int Button_Speak_Eng = 2131165210;
			
			// aapt resource value: 0x7f07000f
			public const int Button_Speak_TurnOn_TurnOff = 2131165199;
			
			// aapt resource value: 0x7f070031
			public const int Deleteword = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int Stats = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int Stats_Flags = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int action_search = 2131165238;
			
			// aapt resource value: 0x7f07001b
			public const int button_E_Next = 2131165211;
			
			// aapt resource value: 0x7f070016
			public const int button_E_choice1 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int button_E_choice2 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int button_E_choice3 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int button_E_choice4 = 2131165209;
			
			// aapt resource value: 0x7f07002a
			public const int button_F_Next = 2131165226;
			
			// aapt resource value: 0x7f070026
			public const int button_F_choice1 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int button_F_choice2 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int button_F_choice3 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int button_F_choice4 = 2131165225;
			
			// aapt resource value: 0x7f070023
			public const int button_F_learn_Next = 2131165219;
			
			// aapt resource value: 0x7f070008
			public const int button_add_word = 2131165192;
			
			// aapt resource value: 0x7f07002b
			public const int button_english = 2131165227;
			
			// aapt resource value: 0x7f070002
			public const int button_english_add = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int button_english_learn = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int button_english_repeat = 2131165187;
			
			// aapt resource value: 0x7f07002c
			public const int button_flags = 2131165228;
			
			// aapt resource value: 0x7f07001e
			public const int button_flags_learn = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int button_flags_repeat = 2131165213;
			
			// aapt resource value: 0x7f07000e
			public const int button_learn_en_ru = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int button_voice = 2131165200;
			
			// aapt resource value: 0x7f070039
			public const int decrease = 2131165241;
			
			// aapt resource value: 0x7f070006
			public const int editText_foreign_word = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int editText_translation_word = 2131165191;
			
			// aapt resource value: 0x7f070021
			public const int imageView_Flags_learn = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int imageView_Flags_repeat = 2131165221;
			
			// aapt resource value: 0x7f070038
			public const int increase = 2131165240;
			
			// aapt resource value: 0x7f070034
			public const int language_eng = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int language_rus = 2131165237;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout1 = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int listViewDelete = 2131165194;
			
			// aapt resource value: 0x7f07002d
			public const int menuDatabase = 2131165229;
			
			// aapt resource value: 0x7f07002f
			public const int menuDatabase_MyDictionary = 2131165231;
			
			// aapt resource value: 0x7f07002e
			public const int menuDatabase_PopularWords = 2131165230;
			
			// aapt resource value: 0x7f070037
			public const int menuDelSort = 2131165239;
			
			// aapt resource value: 0x7f070012
			public const int scrollView1 = 2131165202;
			
			// aapt resource value: 0x7f07001f
			public const int scrollView2 = 2131165215;
			
			// aapt resource value: 0x7f070030
			public const int settings = 2131165232;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int textViewCount = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int textView_Eng_Word = 2131165205;
			
			// aapt resource value: 0x7f070022
			public const int textView_flag_learn = 2131165218;
			
			// aapt resource value: 0x7f07000c
			public const int textView_learn_en = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textView_learn_ru = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int toolbarEnglish = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int toolbarEnglishAdd = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int toolbarEnglishDelete = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int toolbarEnglishLearn = 2131165195;
			
			// aapt resource value: 0x7f070013
			public const int toolbarEnglishRepeat = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int toolbarFlags = 2131165212;
			
			// aapt resource value: 0x7f070020
			public const int toolbarFlagsLearn = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int toolbarFlagsRepeat = 2131165220;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int del_list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int English = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int English_Add = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int English_delete = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int English_Learn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int English_Repeat = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int English_Stat = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Flags = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Flags_Learn = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Flags_Repeat = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_english = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_flags = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int search = 2131099650;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ThemeStat = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int myPopupTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
