#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReLearn.Resource", IsApplication=true)]

namespace ReLearn
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ___ad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ___ae = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ___af = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ___ag = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ___al = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ___am = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ___ao = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ___ar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ___at = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ___au = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ___az = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ___ba = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ___bb = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ___bd = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ___be = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ___bf = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ___bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ___bh = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ___bi = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ___bj = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ___bn = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ___bo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ___br = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ___bs = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ___bt = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ___bw = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ___by = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ___bz = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ___ca = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ___cd = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ___cf = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ___cg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ___ch = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ___ci = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ___ck = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ___cl = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ___cm = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ___cn = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ___co = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ___cr = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ___cu = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ___cv = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ___cy = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ___cz = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ___de = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ___dj = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ___dk = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ___dm = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ___dor = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ___dz = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ___ec = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ___ee = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ___eg = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ___eh = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ___er = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ___es = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ___et = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ___fi = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ___fj = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ___fm = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ___fr = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ___ga = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ___gb = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ___gd = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ___ge = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ___gh = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ___gm = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ___gn = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ___gq = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ___gr = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ___gt = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ___gw = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ___gy = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ___hn = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ___hr = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ___ht = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ___hu = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ___id = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ___ie = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ___il = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ___inn = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ___iq = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ___ir = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ___iss = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ___it = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ___jm = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ___jo = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ___jp = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ___ke = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int ___kg = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ___kh = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ___ki = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ___km = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ___kn = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ___kp = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ___kr = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ___ks = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ___kw = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ___kz = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ___la = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ___lb = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ___lc = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ___li = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ___lk = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ___lr = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ___ls = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int ___lt = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int ___lu = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int ___lv = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int ___ly = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int ___ma = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ___mc = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int ___md = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int ___me = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int ___mg = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int ___mh = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int ___mk = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int ___ml = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int ___mm = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int ___mn = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int ___mr = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int ___mt = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int ___mu = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int ___mv = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int ___mw = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int ___mx = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int ___my = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int ___mz = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int ___na = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int ___ne = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int ___ng = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int ___ni = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int ___nl = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int ___no = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int ___np = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int ___nr = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int ___nu = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int ___nz = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int ___om = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int ___pa = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int ___pe = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int ___pg = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int ___ph = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int ___pk = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int ___pl = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int ___pt = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int ___pw = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int ___py = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int ___qa = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int ___ro = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int ___rs = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int ___ru = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int ___rw = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int ___sa = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int ___sb = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int ___sc = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int ___sd = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int ___se = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int ___sg = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int ___si = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int ___sk = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int ___sl = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int ___sm = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int ___sn = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int ___so = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int ___sr = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int ___ss = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int ___sv = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int ___sy = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int ___sz = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int ___td = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int ___tg = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int ___th = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int ___tj = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int ___tl = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int ___tm = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int ___tn = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int ___to = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int ___tr = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int ___tt = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int ___tv = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int ___tw = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int ___tz = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int ___ua = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int ___ug = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int ___us = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int ___uy = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int ___uz = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int ___va = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int ___vc = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int ___ve = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int ___vn = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int ___vu = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int ___ws = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int ___ye = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int ___za = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int ___zm = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int ___zw = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int arrow = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int backgroundEnFl = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int backgroundMain = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int button_enabled = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int button_false = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int button_touch = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int button_true = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int buttonAfterClicking = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int buttonBeforeClicking = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int icon_new = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int mainBackGround = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int MainRelearn = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int relearnMain = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int settings = 2130837715;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002c
			public const int Deleteword = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int Stats = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int Stats_Flags = 2131165230;
			
			// aapt resource value: 0x7f070031
			public const int action_search = 2131165233;
			
			// aapt resource value: 0x7f070018
			public const int button_E_Next = 2131165208;
			
			// aapt resource value: 0x7f070014
			public const int button_E_choice1 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int button_E_choice2 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int button_E_choice3 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int button_E_choice4 = 2131165207;
			
			// aapt resource value: 0x7f070027
			public const int button_F_Next = 2131165223;
			
			// aapt resource value: 0x7f070023
			public const int button_F_choice1 = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int button_F_choice2 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int button_F_choice3 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int button_F_choice4 = 2131165222;
			
			// aapt resource value: 0x7f070020
			public const int button_F_learn_Next = 2131165216;
			
			// aapt resource value: 0x7f070008
			public const int button_add_word = 2131165192;
			
			// aapt resource value: 0x7f070029
			public const int button_english = 2131165225;
			
			// aapt resource value: 0x7f070002
			public const int button_english_add = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int button_english_learn = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int button_english_repeat = 2131165187;
			
			// aapt resource value: 0x7f07002a
			public const int button_flags = 2131165226;
			
			// aapt resource value: 0x7f07001b
			public const int button_flags_learn = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int button_flags_repeat = 2131165210;
			
			// aapt resource value: 0x7f07000e
			public const int button_learn_en_ru = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int editText_foreign_word = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int editText_translation_word = 2131165191;
			
			// aapt resource value: 0x7f07001e
			public const int imageView_Flags_learn = 2131165214;
			
			// aapt resource value: 0x7f070022
			public const int imageView_Flags_repeat = 2131165218;
			
			// aapt resource value: 0x7f07002f
			public const int language_eng = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int language_rus = 2131165232;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout1 = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int listViewDelete = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int scrollView1 = 2131165200;
			
			// aapt resource value: 0x7f07001c
			public const int scrollView2 = 2131165212;
			
			// aapt resource value: 0x7f07002b
			public const int settings = 2131165227;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int textViewCount = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int textView_Eng_Word = 2131165203;
			
			// aapt resource value: 0x7f07001f
			public const int textView_flag_learn = 2131165215;
			
			// aapt resource value: 0x7f07000c
			public const int textView_learn_en = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textView_learn_ru = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int toolbarEnglish = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int toolbarEnglishAdd = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int toolbarEnglishDelete = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int toolbarEnglishLearn = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int toolbarEnglishRepeat = 2131165201;
			
			// aapt resource value: 0x7f070019
			public const int toolbarFlags = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int toolbarFlagsLearn = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int toolbarFlagsRepeat = 2131165217;
			
			// aapt resource value: 0x7f070028
			public const int toolbarMainActivity = 2131165224;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int del_list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int English = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int English_Add = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int English_delete = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int English_Learn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int English_Repeat = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int English_Stat = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Flags = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Flags_Learn = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Flags_Repeat = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_english = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_flags = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int search = 2131099650;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ThemeStat = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int myPopupTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
